# Generated by Django 5.0.3 on 2024-04-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbkquizz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Points',
        ),
    ]
