# Generated by Django 5.0.3 on 2024-04-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbkquizz', '0002_usersettings_points_delete_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_notes',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
