# Generated by Django 5.0.3 on 2024-04-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbkquizz', '0003_question_question_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
