# Generated by Django 5.0.3 on 2024-04-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbkquizz', '0004_rename_question_notes_question_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='notes',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
