# Generated by Django 5.0.3 on 2024-04-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbkquizz', '0005_alter_question_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
