# Generated by Django 5.0.3 on 2024-12-03 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbkquizz', '0008_globalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='currentQuestion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fbkquizz.question'),
        ),
    ]
