# Generated by Django 5.0.3 on 2024-12-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbkquizz', '0010_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('0', 'info'), ('1', 'regular')], max_length=256),
        ),
    ]
