# Generated by Django 5.0.3 on 2024-12-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbkquizz', '0013_alter_question_text_alter_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
