# Generated by Django 5.0.3 on 2024-12-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbkquizz', '0014_question_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
