# Generated by Django 5.0.3 on 2025-01-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbkquizz', '0015_question_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='timer',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('info', 'info'), ('multipleChoice', 'multipleChoice')], max_length=256),
        ),
    ]
