# Generated by Django 5.0.3 on 2025-01-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbkquizz', '0016_globalsettings_timer_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
