# Generated by Django 5.0.3 on 2025-01-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbkquizz', '0017_question_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
