# Generated by Django 5.0.3 on 2025-07-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbkquizz', '0018_usersettings_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
