# Generated by Django 5.0.3 on 2025-07-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbkquizz', '0019_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='accepted_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('info', 'info'), ('multipleChoice', 'multipleChoice'), ('freeText', 'freeText')], max_length=256),
        ),
    ]
