# Generated by Django 5.0.3 on 2025-07-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbkquizz', '0021_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('info', 'info'), ('multipleChoice', 'multipleChoice'), ('freeText', 'freeText'), ('userChoice', 'userChoice')], max_length=256),
        ),
    ]
