# Generated by Django 5.0.3 on 2025-07-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbkquizz', '0022_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='muted_until_round',
            field=models.IntegerField(default=0),
        ),
    ]
