[variables]
NODE_VERSION = "18"
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.build] 
cmds = [
  # Install Node.js dependencies for frontend
  "cd frontend && npm install",
  # Build React frontend
  "cd frontend && NODE_ENV=production npm run build",
  # Create static directory structure for Django
  "mkdir -p static/frontend",
  "cp -r frontend/dist/* static/frontend/",
  # Collect Django static files
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "python manage.py migrate && gunicorn fabrikots.wsgi:application --bind 0.0.0.0:$PORT"