[variables]
NODE_VERSION = "18"
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.build]
cmds = [
  "cd frontend && npm install",
  "cd frontend && npm run build",
  "mkdir -p static/frontend", 
  "cp -r frontend/dist/* static/frontend/"
]