[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn fabrikots.wsgi:application --bind 0.0.0.0:$PORT"

[env]
NODE_VERSION = "18"
NIXPACKS_PYTHON_VERSION = "3.11"
NODE_ENV = "production"
SRC_ENV = "PRODUCTION"